### ISSUE TITLE
UnoCSS Prest (port)

### ISSUE THREAD

**Issue by whatnickcodes** [romboHQ/tailwindcss-motion#1]
Super beautiful library. Thank you. An UnoCSS preset would be awesome to see too

**Comment by nicksmithr** [comment]
Hey Nick, thanks for the suggestion here! It's probably not a big priority for us now, neither @KevinGrajeda nor I have really built with UnoCSS before so we're probably not in the best place to build it. 

But we'll keep it on our radar as Uno grows 🚀

**Comment by whatnickcodes** [comment]
Totally. I might take a poke at it and let you know

**Comment by nicksmithr** [comment]
Do it! 🚀 drop us a line for any guidance :)On 8 Oct 2024, at 18:33, Nicholas Cerminara ***@***.***> wrote:﻿
Totally. I might take a poke at it and let you know

**Comment by whatnickcodes** [comment]
So I ended up finishing this with full support.

Just want to say seriously beautiful library after the deep dive. Super clever/creative use of the variables.

I'll make a cool page and drop the link next week here.

**Comment by whatnickcodes** [comment]
Boom! https://github.com/whatnickcodes/unocss-preset-tailwindcss-motion

I'm not sure if there's spot for this anywhere for reference. I'll bug the UnoCSS community preset folks about adding it to their site too
