### ISSUE TITLE
is there any cdn?

### ISSUE THREAD

**Issue by Shuhib1924** [romboHQ/tailwindcss-motion#26]
hi guys,

i'd like to know it is possible to use tailwind-motion as cdn for simple setup?

**Comment by Shuhib1924** [comment]
many thanks :)

**Comment by Shuhib1924** [comment]
i've tried to use it with your shopify teplate, but unfortunately it doesn't works

`<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        >
        <script
            src="https://cdn.skypack.dev/tailwindcss-motion?min"
            defer
        ></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <title>Document</title>
    </head>

    <body>
        <div class="bg-black h-screen text-white overflow-y-auto">
            <header class="flex justify-between items-center p-4">
                <a
                    href="https://rombo.co/"
                    class="font-black text-2xl motion-preset-slide-down"
                >Rombo</a>
                <nav class="flex gap-6 mr-4 font-semibold">
                    <a
                        href="https://rombo.co/"
                        class="motion-delay-[400ms] motion-preset-rebound-down"
                    >Products</a>
                    <a
                        href="https://rombo.co/"
                        class="motion-delay-[450ms] motion-preset-rebound-down"
                    >Learn More</a>
                    <a
                        href="https://rombo.co/"
                        class="motion-delay-[500ms] motion-preset-rebound-down"
                    >Contact Us</a>
                </nav>
            </header>
            <main class="mx-auto px-8 py-4 max-w-4xl overflow-x-hidden">
                <h2 class="flex-wrap opacity-70 pb-6 font-bold text-xl motion-delay-[700ms] motion-preset-fade">
                    SOLUTIONS</h2>
                <div class="flex sm:flex-row flex-col gap-10 sm:gap-4 mt-10">
                    <div
                        class="motion-preset-slide-left flex-1 bg-lime-800/50 p-4 rounded-2xl motion-ease-spring-bouncier motion-delay-[1000ms] motion">
                        <img
                            alt="shopify logo"
                            class="bg-blend-exclusion -mt-12 mb-4 size-20"
                            src="https://cdn.sanity.io/images/xrq4swux/production/ea11cf5ade02dbf180e5a8c277a281141d58d6f4-110x124.svg?fit=max&auto=format"
                        />
                        <h3 class="mb-2 font-bold text-2xl">Shopify</h3>
                        <p class="opacity-80 text-sm">Join thousands of Shopify users bringing their stores to life with
                            Rombo.
                        </p>
                    </div>
                    <div
                        class="motion-preset-slide-left flex-1 bg-teal-800/50 p-4 rounded-2xl motion-ease-spring-bouncier motion-delay-[1300ms] motion">
                        <img
                            alt="tailwind logo"
                            class="bg-blend-exclusion opacity-90 -mt-12 mb-4 size-20"
                            src="https://cdn.sanity.io/images/xrq4swux/production/49f386e7cb98664a6645577735448c1062daeb57-54x33.svg?fit=max&auto=format"
                        />
                        <h3 class="mb-2 font-bold text-2xl">TailwindCSS</h3>
                        <p class="opacity-80 text-sm">Add intricate animations to your frontend in no time at all.</p>
                    </div>
                    <div
                        class="motion-preset-slide-left flex-1 bg-gray-800/50 p-4 rounded-2xl motion-ease-spring-bouncier motion-delay-[1600ms] motion">
                        <img
                            alt="figma logo"
                            class="bg-blend-exclusion opacity-90 -mt-12 mb-4 size-20"
                            src="https://cdn.sanity.io/images/xrq4swux/production/8ba9090052032bc90e8cfa9a83583fdf69c7d96b-413x620.svg?fit=max&auto=format"
                        />
                        <h3 class="mb-2 font-bold text-2xl">Figma</h3>
                        <p class="opacity-80 text-sm">Add interactivity to your designs without leaving the Figma
                            canvas.</p>
                    </div>
                </div>
                <p class="flex flex-wrap gap-4 mt-8 font-black text-4xl md:text-6xl">
                    <span class="block motion-preset-blur-left motion-delay-[2400ms]">MOTION</span>
                    <span class="block motion-preset-blur-left motion-delay-[2800ms]">WITHOUT</span>
                    <span class="block motion-preset-blur-left motion-delay-[3200ms]">COMMOTION</span>
                </p>
                <p class="mt-4 font-thin motion-delay-[4s] motion-preset-fade-lg">Lorem ipsum dolor sit amet,
                    consectetur
                    adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                    veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                    dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                    occaecat
                    cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
                <p class="mt-4 font-thin motion-delay-[4s] motion-preset-fade-lg">Lorem ipsum dolor sit amet,
                    consectetur
                    adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                    veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                    dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                    occaecat
                    cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
            </main>
        </div>

    </body>

</html>`

**Comment by Shuhib1924** [comment]
even with the example of rombo documents it doesn't work

`
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        >
        <script src="https://cdn.skypack.dev/tailwindcss-motion"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <title>Document</title>
        <script>
            /** @type {import('tailwindcss').Config} */
            module.exports = {
                plugins: [require('tailwindcss-motion')],
            };
        </script>
    </head>

    <body>
        <div class="bg-red-400 motion-preset-pulse-sm size-20">
            Pulse animation
        </div>
    </body>

</html>
`

**Comment by quick007** [comment]
Ah ok, based on your original question I didn't know about your use case and wasn't sure what you meant by is there a cdn. The tailwind docs have some basic info [on how to add plugins using the play cdn](https://tailwindcss.com/docs/installation/play-cdn), though it looks like it only supports first-party plugins.

I would strongly recommend a more traditional setup [using the tailwind CLI](https://tailwindcss.com/docs/installation) which doesn't require any complex bundlers and works out of the box. It also easily supports tailwindcss-motion and will have faster load times for your intended user. FYI, the play cdn you're using right now is very much not intended for production deployments so migrating to the CLI is the preferred option.

**Comment by KevinGrajeda** [comment]
As @quick007 said, I would also recommend a more traditional Tailwind setup, but if you need to use the plugin with a CDN, you can do something like this https://codepen.io/kevin-carlos-grajeda-a/pen/OJKPBPj

**Comment by Shuhib1924** [comment]
many thanks, yeah i use tailwind standalone setup without node... but sometimes its more easier to test something via cdn, you know :)

and thanks once again, now i know how to setup all other plugins as well 👍

**Comment by Shuhib1924** [comment]
according me its a very great solution to get the static files from htmx for requests, alpineJS for interactions, tailwind for stylesheets and now even with rombo for great and simple animations 

i'm asking myself, when i setup tailwind by CLI, do i get all animations as css file?

**Comment by quick007** [comment]
Tailwind exports a css file with all of the classes- animations included. I don't know of a way to easily create a separate CSS file without animations besides just writing a script that extracts all classes starting with `motion`, but Kevin might have a better solution.

FYI, [tailwind can run standalone without node](https://tailwindcss.com/docs/v4-beta#:~:text=You%20can%20also%20download%20standalone%20builds%20of%20the%20new%20CLI%20tool%20from%20GitHub%20for%20projects%20that%20don%E2%80%99t%20otherwise%20depend%20on%20the%20Node.js%20ecosystem.) (this may only work with tailwind 4 though). Granted, based on the structure of your project, I don't understand why you can't use node. Tailwind doesn't run during runtime, only when you're building. The most basic solution would be to set up a simple CI that generates the tailwind classes. You could also use pre-commit hooks and do it on push (though this isn't an optimal solution).

**Comment by Shuhib1924** [comment]
thanks for your reply,

one issue should be corrected, the standalone variant works in all versions, it's just the runtime without the Node overhead.... back to your question, why i prefer to use it without node, its because i'm using often django, fastapi or rust as backend, therefore for all non-JS SSR architecture, it's easier to handle it without node, just the static files are the best 🥸
