### ISSUE TITLE
Typewriter effect runs infinite

### ISSUE THREAD

**Issue by kobeaerts** [romboHQ/tailwindcss-motion#6]
Hey, cool library!

Is it possible to run the typewriter effect only once?
And is it possible to remove the blinking effect?

**Comment by KevinGrajeda** [comment]
We just added the ability to tweak looping animations with motion-loop-[loop count]. Now, you can use motion-loop-once or motion-loop-[1.5] to create different effects. 
example: https://play.tailwindcss.com/dgdVxyFPWh

And the possibility of removing the blinking effect isn't on our radar for now. Sorry about that

**Comment by hamboomger** [comment]
Would be great to update site or documentation, didn't see any mention of loop anywhere.

**Comment by porobertdev** [comment]
`motion-preset-shake motion-loop-infinite` doesn't seems to work:

```
<div
  class="whatsapp-bubble bg-primary rounded-md p-2 cursor-pointer motion-preset-shake motion-loop-infinite"
></div>
```
