### ISSUE TITLE
Tailwind v4 support & docs

### ISSUE THREAD

**Issue by itsezc** [romboHQ/tailwindcss-motion#8]
Added support for Tailwind v4 and documentation of the setup process

**Comment by KevinGrajeda** [comment]
We are waiting for version 4 to be out of alpha. Once it is out, we will check its support 🫡

**Comment by pete-willard** [comment]
https://tailwindcss.com/blog/tailwindcss-v4-beta :)

**Comment by KevinGrajeda** [comment]
You can now use the plugin with Tailwind v4 https://docs.rombo.co/tailwind/installation

**Comment by dany68** [comment]
Hi,
Thank you very much for your work.
It seems that when using tailwind v4 i must use --legacy-peer-deps. Is it expected ?
